Avoid error on first opening.
The first time you load this plugin, it will always print an error:

```
ERROR: Request for nonexistent project setting: filesystem/import/blend/blender_path.
```

It seems that `set_setting` must be called before `set_initial_value`,
as the latter expect the setting to already exist.

See: https://github.com/godotengine/godot/blob/406e26abeb31f76a401762e82d5640f5d73e7902/core/config/project_settings.cpp#L199